### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by Itsfoss0** [FrkdUp/AudioVerseAPI#1]
I have notice in the [installation guide](https://github.com/RandSofts/AudioVerseAPI/blob/main/README.md#installation), its mentioned that one should run ```pip install -r requirements.txt``` in the root of the repo after cloning it. This however does not work as expected since a ```requirements.txt``` file doesn't exits in the root of the repository. Consider updating the instructions or adding the required package names and versions in  a ```requirements.txt``` file in the root. 

![Screenshot of the error message](https://user-images.githubusercontent.com/105123601/231960527-8eba955c-68a7-4408-ab21-fca5ae8a9ebe.png)

**Comment by ItsNotAlexy** [comment]
Hello @itsfoss0 Thanks for opening a issue! I have looked at the code and yes there was not a requirements.txt in the repo yet. I will quickly fix the repo and you can re-clone the repo with the new updates. Thanks!

**Comment by ItsNotAlexy** [comment]
The file has been created, And it should be working now. Please dont hesitate to make a new issue if another problem prevails.

**Comment by Itsfoss0** [comment]
@ItsNotAlexy  All good now.
Thanks for fixing so quickly.

**Comment by ItsNotAlexy** [comment]
> @ItsNotAlexy  All good now.
> Thanks for fixing so quickly. 

No problem! ❤️
